spring.datasource.url=jdbc:postgresql://dpg-d7edmdd7vvec73f63uag-a.singapore-postgres.render.com:5432/employee_db_4xmx
spring.datasource.username=employee_db_4xmx_user
spring.datasource.password=qtAmGqrcV45jy7qURAj8wv8eBAtUNRSq

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

cors.allowed-origins=*
cors.allowed-methods=*
cors.allowed-headers=*
cors.exposed-headers=*